[package]
name = "tsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
notify = "6.0.1"
rpassword = "7.2.0"
ssh2 = "0.9.4"
walkdir = "2.3.3"
